### ISSUE TITLE
Use correct size from image url

### ISSUE THREAD

**Issue by torbencarstens** [tim-hat-die-hand-an-der-maus/preliminary-frontend#12]
`movie.imdb.coverUrl.rsplit("@", 1)`

lazy loading

**Comment by BjoernPetersen** [comment]
Bump

**Comment by BjoernPetersen** [comment]
Could you prioritize this?

**Comment by BjoernPetersen** [comment]
This is blocking important processes! (My sense of aesthetics)

**Comment by BjoernPetersen** [comment]
Real talk: shouldn't this happen in the imdb-resolver?

**Comment by torbencarstens** [comment]
I actually want to do this in the frontend since the load-times will go down. The removal of the actual size can happen in imdb-resolver.

**Comment by BjoernPetersen** [comment]
I don't understand, what do you want to do where? (Keep in mind that I refuse to have a look at the frontend code)

**Comment by torbencarstens** [comment]
`imdb-resolver` removes the size from the cover url, but then we'd load the full size image in the frontend which isn't necessary since we'll never display a full size cover.

That's why I want to add the actual dimensions (which are set in the frontend anyways) so we have fewer resources to load -> better loading times/less bandwidth waste/no resizing necessary.

**Comment by BjoernPetersen** [comment]
So does `imdb-resolver` already remove the size from the URL, or do we need to create an issue for that?

**Comment by torbencarstens** [comment]
https://github.com/tim-hat-die-hand-an-der-maus/imdb-resolver/pull/6

**Comment by torbencarstens** [comment]
I actually need the image size ratio or original width and height.
Maybe we should convert `coverUrl` to

```json
cover: {
  "url": "<String>",
  "width": <int>,
  "height": <int>
}
```

or replace width/height with `ratio: <float>`

what do you think?

**Comment by BjoernPetersen** [comment]
I think ratio is probably the best solution

**Comment by torbencarstens** [comment]
additionally:

`_V1_SY150_CR0,0,101,150_` no idea what CR does, doesn't seem to affect the output (visually at least)

SY150 is the height of the image, `S` can apparently be replaced with `U`, I couldn't find any differences in those two.
Other characters seem to just ignore the size and show the given width/height based from the top left.

If `Y` is replaced by `X` it takes the width for stretching.
